version: '3.9'

services:
  web:
    container_name: web
    build:
      context: ./app
    ports:
      - '8080:80'
      - '5173:5173'
    volumes:
      - ../sports_site_app:${WEB_PATH}
    depends_on:
      - db
      - db-nfl
  db:
    image: postgres:15.1
    container_name: db
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${ROOT_PASSWORD}
      POSTGRES_DB: ${DATABASE}
      TZ: ${TZ}
    volumes:
      - db-data:${DB_PATH}
    ports:
      - 5432:5432
  db-nfl:
    image: postgres:15.1
    container_name: db-nfl
    environment:
      POSTGRES_USER: ${NFL_USER}
      POSTGRES_PASSWORD: ${NFL_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${NFL_ROOT_PASSWORD}
      POSTGRES_DB: ${NFL_DATABASE}
      TZ: ${NFL_TZ}
    volumes:
      - db-data-nfl:${NFL_DB_PATH}
    ports:
      - 5433:5432
volumes:
  db-data:
  db-data-nfl:
